export enum EVENTS {
  CHIP_COLLECTED = "CHIP_COLLECTED",
  CHIP_REMOVED = "CHIP_REMOVED",
  CHIPS_DROPPED = "CHIPS_DROPPED",
  CHIP_POINTED = "CHIPS_DROPPED",
  CHIPS_SWAPPED = "CHIPS_DROPPED",
  CHIPS_START_SWAP = "CHIPS_START_SWAP",
  UI_READY = "UI_READY",
  UI_CHOOSE_DIF = "UI_CHOOSE_DIF",
  SHUFFLE = "SHUFFLE",
  AWAIT_USER_ACTION = "AWAIT_USER_ACTION",
  USER_ACTION_SWAP = "USER_ACTION_SWAP",
  USER_ACTION_SHUFFLE = "USER_ACTION_MOVE",
}

export class EventBusComponent extends Phaser.Events.EventEmitter { }